// _Settings_EOArchive_English.java
// Generated by EnterpriseObjects palette at Friday, December 30, 2005 11:36:41 PM America/Denver

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _Settings_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOView _iBCarbonButton0, _iBCarbonButton1, _iBCarbonCheckBox0, _iBCarbonCheckBox1, _iBCarbonCheckBox2, _iBCarbonCheckBox3, _iBCarbonCheckBox4, _iBCarbonCheckBox5, _iBCarbonCheckBox6, _iBCarbonSlider0, _iBCarbonStaticText0, _iBCarbonStaticText1;
    javax.swing.JPanel _iBCarbonRootControl0;

    public _Settings_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _iBCarbonButton1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonButton0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonCheckBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonCheckBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonCheckBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonCheckBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonStaticText1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonSlider0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonStaticText0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonCheckBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonCheckBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBCarbonCheckBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Settings");
        _iBCarbonRootControl0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
    }

    protected void _init() {
        super._init();
        if (!(_iBCarbonRootControl0.getLayout() instanceof EOViewLayout)) { _iBCarbonRootControl0.setLayout(new EOViewLayout()); }
        _iBCarbonCheckBox0.setSize(382, 22);
        _iBCarbonCheckBox0.setLocation(11, 12);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonCheckBox0, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonCheckBox0);
        _iBCarbonCheckBox1.setSize(382, 22);
        _iBCarbonCheckBox1.setLocation(11, 36);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonCheckBox1, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonCheckBox1);
        _iBCarbonCheckBox2.setSize(382, 22);
        _iBCarbonCheckBox2.setLocation(11, 60);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonCheckBox2, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonCheckBox2);
        _iBCarbonStaticText0.setSize(48, 16);
        _iBCarbonStaticText0.setLocation(13, 88);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonStaticText0, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonStaticText0);
        _iBCarbonSlider0.setSize(267, 25);
        _iBCarbonSlider0.setLocation(67, 87);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonSlider0, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonSlider0);
        _iBCarbonStaticText1.setSize(48, 16);
        _iBCarbonStaticText1.setLocation(340, 88);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonStaticText1, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonStaticText1);
        _iBCarbonCheckBox3.setSize(382, 22);
        _iBCarbonCheckBox3.setLocation(11, 118);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonCheckBox3, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonCheckBox3);
        _iBCarbonCheckBox4.setSize(382, 22);
        _iBCarbonCheckBox4.setLocation(11, 142);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonCheckBox4, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonCheckBox4);
        _iBCarbonCheckBox5.setSize(382, 22);
        _iBCarbonCheckBox5.setLocation(11, 166);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonCheckBox5, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonCheckBox5);
        _iBCarbonCheckBox6.setSize(382, 22);
        _iBCarbonCheckBox6.setLocation(11, 190);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonCheckBox6, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonCheckBox6);
        _iBCarbonButton0.setSize(82, 32);
        _iBCarbonButton0.setLocation(230, 226);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonButton0, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonButton0);
        _iBCarbonButton1.setSize(82, 32);
        _iBCarbonButton1.setLocation(312, 226);
        ((EOViewLayout)_iBCarbonRootControl0.getLayout()).setAutosizingMask(_iBCarbonButton1, EOViewLayout.MinYMargin);
        _iBCarbonRootControl0.add(_iBCarbonButton1);
        _iBCarbonRootControl0.setSize(401, 264);
        _eoFrame0.setTitle("x264 Settings");
        _eoFrame0.setLocation(183, 466);
        _eoFrame0.setSize(401, 264);
    }
}
